### ISSUE TITLE
Mouse/Window Position Suggestions

### ISSUE THREAD

**Issue by Tiddalick** [NoOneBlood/xmapedit#1]
Firstly, thank you for your work on making editing a much nicer experience!

Two suggestions for any future updates:
1. The window always seems to render on the bottom right of my screen but seems to assume the window size will be 1024x768? I always need to drag the window up to display the entire workspace.
2. The mouse is captured by the program. Is it possible to have a setting in the .ini file to disable this? As I am trying to learn from other examples I often need to change control to other windows.

**Comment by NoOneBlood** [comment]
If you downloaded Jan 27 2024 release (https://github.com/NoOneBlood/xmapedit/releases/tag/Xmapedit-Build-Jan-27-2024) from this site, it has wrong files attached (the ones from Jan 25 2024 release). Try to download most recent build i just posted.
That should fix the problem.

**Comment by Tiddalick** [comment]
Hi,

I can confirm that the latest build fixes the weird positioning error at the bottom of the screen.

I would still request that in a future update that the there is an option to unbound the mouse from the window. :)

**Comment by NoOneBlood** [comment]
You should be able to unbound it with just Alt-Tab. If (for some weird reason) it does not working for you, try to press ~ (tilde) key. This should release mouse cursor and you will able to move it anywhere
