### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by Tiddalick** [NoOneBlood/xmapedit#2]
Hi there,

The autosave function seems to be a bit temperamental.
It works fine for a Newboard.map and saves in the location that I work from (..\Maps\)
However, when I "save as" it seems to have issues.
I have tried filenames of 6 and 8 characters long and it seems to be the same issue. It will show the icon of autosaving, but then it doesn't actually save anything that I can find.

Additionally it sometimes reports weird characters:
![image](https://github.com/NoOneBlood/xmapedit/assets/32033640/90976f1c-738c-4c25-9393-31b47605c3aa)

**Comment by NoOneBlood** [comment]
Autosave files always appearing in the folder where map is loaded from, So if you loaded map from /Maps directory, you should expect that ASAVE file will appear in there. It also uses only filename instead of full path. The bug you just metioned here should be fixed in the most recent release.

**Comment by Tiddalick** [comment]
Hi,

Thanks, the latest build has fixed this problem. Closing this issue.
