### ISSUE TITLE
Key Summary

### ISSUE THREAD

**Issue by Tiddalick** [NoOneBlood/xmapedit#3]
Hi,

Is there a spot in the code that details all the keys, both existing and those added for the extended functions?

I have been trying to build a document for myself that lists all the keys so I can better understand what is possible, but pre-existing 
documents are for MapEdit and these conflict with the changes and additions that have been included in XMapedit.

I know that new additions are written in the patch notes, but do they exist in a summary anywhere?

**Comment by Tiddalick** [comment]
Well I had a go at making one myself, copying the style of the .txt files for ART edit and SEQ edit.
Here it is in case it is useful.

[XMapeditKeys.txt](https://github.com/NoOneBlood/xmapedit/files/15374084/XMapeditKeys.txt)

**Comment by NoOneBlood** [comment]
A temporary link can be found here
https://drive.google.com/file/d/1PEuymcpiS14gnQb9K77qB5-J594Y-Msq/view

The guy is actually working on full offline version of the manual that (hopefully) will be included in release package sooner or later. You can find it on discord channel https://discord.com/invite/V9fY5wE

Your key list looks very nice too, thanks for making it.

**Comment by Tiddalick** [comment]
Thanks for the reply.
It was a useful exercise for myself regardless to familiarise myself with the keys.

Given there will be a version coming in the manual I think this can be closed.
