### ISSUE TITLE
Request: Key Binding

### ISSUE THREAD

**Issue by Tiddalick** [NoOneBlood/xmapedit#4]
Hello,

As I have used this program for a while now, I have a feature request that might be useful.

Would it be possible to add an .ini option that adds in a toggle key (say [3]) that when pressed disables the normal function of the WASD keys and replaces their function to that of the ARROW keys. 

Maybe this could also change the white arrow color to show that this toggle is enabled. This would allow my left hand to stay where it is needed, rather than constantly moving it.

Also, could the MOUSE SCROLL replicate the A/Z functionality in 3D mode.

**Comment by CommonLoon102** [comment]
As a workaround, if you are on Windows, you can use AutoHotkey.

**Comment by NoOneBlood** [comment]
A basic key mapper file which should partially do what you need to, will be available with the next update.
I will think about adding a key to toggle it

**Comment by Tiddalick** [comment]
Thanks for the feedback and the insight in what is coming.

A key mapper file would be quite useful to also act as a definitive source on the keys that are available.

Anything that might support more mouse focused interaction over the original keyboard I think is only a positive thing.

**Comment by CommonLoon102** [comment]
@Tiddalick You should only close this when the code is already in the master branch.
